name: ${project.name}
version: ${project.version}
main: ${main.class}
author: ${author}
api-version: 1.13

softdepend: [WorldGuard, PlaceholderAPI]

permissions:
  dib.help:        { default: op }
  dib.reload:      { default: op }
  dib.toggle:      { default: op }
  dib.status:      { default: op }
  dib.list:        { default: op }
  dib.block:       { default: op }
  dib.unblock:     { default: op }
  dib.check:       { default: op }
  dib.stats:       { default: op }
  dib.stats.reset: { default: op }
  dib.gui:         { default: op }
  dib.notify:      { default: op }
  dib.bypass:
    default: false
    children:
      dib.bypass.world.*: true
      dib.bypass.region.*: true
      dib.bypass.item.*: true

commands:
  dib:
    description: Comando principal de DesidiaItemCraftBlock
    usage: /dib help
    permission: dib.help
